import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { BsFacebook } from "react-icons/bs";
import { AiFillLinkedin, AiOutlineGithub } from "react-icons/ai";
import Image from "next/image";
import { LazyLoadImage } from "react-lazy-load-image-component";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        data-theme="mytheme"
        className="min-h-screen bg-gradient-to-b from-accent to-neutral text-base-100"
      >
        <div className="relative mx-auto w-[calc(100%-16px)] max-w-[1200px]">
          <div className="flex items-center justify-between py-4">
            <div className="text-xl text-base-100 md:text-2xl">
              <span className="text-primary">Dat</span>isekai
            </div>
            <button className="btn-primary btn text-base-100">Login</button>
          </div>

          <div className="mt-5 flex space-x-4 flex-col md:flex-row justify-between">
            <div className="w-full space-y-4 md:w-[30%]">
              <p className="text-2xl md:text-4xl">Chào bạn, mình là </p>
              <p className="text-4xl text-primary md:text-6xl">Datisekai</p>
              <p className="text-2xl leading-5 md:text-4xl">
                Intern Frontend Developer
              </p>
              <div className="leading-8">
                <p>
                  Mình là Đạt, sinh viên trường Đại Học Sài Gòn, chuyên ngành Kĩ
                  Thuật Phần Mềm.
                </p>
                <p>
                  Mình thích code, học hỏi nhiều thứ mới. Ngoài ra thì mình còn
                  thích bóng bàn, cầu lông, LQM, PUBG,..
                </p>
                <p>
                  Đặc biệt là mình{" "}
                  <span className="text-primary">độc thân</span> nhaa
                </p>
              </div>
              <div className="flex space-x-2">
                <button className="btn-outline btn-primary btn gap-2">
                  <BsFacebook />
                  Facebook
                </button>
                <button className="btn-outline btn-primary btn gap-2">
                  <AiFillLinkedin />
                  Linkedin
                </button>
                <button className="btn-outline btn-primary btn gap-2">
                  <AiOutlineGithub />
                  Github
                </button>
              </div>
            </div>
            <div className="flex flex-1 flex-col md:flex-row justify-end">
              <div className="">
                <LazyLoadImage
                  src="/images/me.jpg"
                  className="w-full rounded-bl-2xl rounded-tl-2xl md:w-[500px]"
                  alt="Datisekai"
                />
              </div>
              <div className="stats stats-vertical rounded-tl-none rounded-bl-none shadow">
                <div className="stat">
                  <div className="stat-title">Ngày sinh</div>
                  <div className="stat-value">03</div>
                  <div className="stat-desc">01/2002</div>
                </div>

                <div className="stat">
                  <div className="stat-title">Địa chỉ</div>
                  <div className="stat-value">222</div>
                  <div className="stat-desc">Võ Thành Trang</div>
                </div>

                <div className="stat">
                  <div className="stat-title">Năm học</div>
                  <div className="stat-value">3</div>
                  <div className="stat-desc">SGU</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
